const places = [
  {
    id: 1,
    name: "Sigiriya",
    description: "Ancient rock fortress and UNESCO World Heritage Site.",
    image: "/assets/images/sigiriya.jpg",
    lat: 7.9574,
    lng: 80.7600,
  },
  {
    id: 2,
    name: "Ella",
    description: "Scenic mountain town with hiking trails and waterfalls.",
    image: "/assets/images/ella.jpg",
    lat: 6.8667,
    lng: 81.0450,
  },
  {
    id: 3,
    name: "Galle Fort",
    description: "Historic fort and old city with colonial architecture.",
    image: "/assets/images/galle-fort.jpg",
    lat: 6.0328,
    lng: 80.2170,
  },
  {
    id: 4,
    name: "Nuwara Eliya",
    description: "Cool hill station known for tea plantations and gardens.",
    image: "/assets/images/nuwara-eliya.jpg",
    lat: 6.9497,
    lng: 80.7890,
  },
  {
    id: 5,
    name: "Yala National Park",
    description: "Wildlife sanctuary famous for leopards and elephants.",
    image: "/assets/images/yala.jpg",
    lat: 6.3619,
    lng: 81.5480,
  },
  {
    id: 6,
    name: "Polonnaruwa",
    description: "Ancient city with well-preserved ruins and temples.",
    image: "/assets/images/polonnaruwa.jpg",
    lat: 7.9394,
    lng: 81.0000,
  },
  {
    id: 7,
    name: "Adam's Peak",
    description: "Sacred mountain with a footprint rock revered by multiple religions.",
    image: "/assets/images/adams-peak.jpg",
    lat: 6.8039,
    lng: 80.4990,
  },
  {
    id: 8,
    name: "Mirissa",
    description: "Beautiful beach town known for whale watching and surfing.",
    image: "/assets/images/mirissa.jpg",
    lat: 5.9480,
    lng: 80.4540,
  },
  {
    id: 9,
    name: "Anuradhapura",
    description: "Ancient city with well-preserved ruins and stupas.",
    image: "/assets/images/anuradhapura.jpg",
    lat: 8.3114,
    lng: 80.4037,
  },
  {
    id: 10,
    name: "Trincomalee",
    description: "Harbor city with beautiful beaches and historic temples.",
    image: "/assets/images/trincomalee.jpg",
    lat: 8.5870,
    lng: 81.2152,
  },
  {
    id: 11,
    name: "Horton Plains",
    description: "National park with scenic hiking trails and World's End cliff.",
    image: "/assets/images/horton-plains.jpg",
    lat: 6.8000,
    lng: 80.8000,
  }
];

export default places;
